export const ROUTES = {
  AUTH: {
    BASE: '/auth',
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/me/password',
    CHANGE_USERNAME: '/auth/me/username',
    CHANGE_PHOTO: '/auth/me/photo',
    CHANGE_EMAIL: '/auth/me/email',
  },
  TRADING: {
    PRIVATE_BALANCE: '/trading/private/balance',
    ORDERS: '/trading/orders',
    ORDER_BY_ID: (orderId: number) => `/trading/orders/${orderId}`,
    WATCHLIST: '/trading/watchlist',
    WATCHLIST_BY_STOCK: (stockId: string) => `/trading/watchlist/${stockId}`,
    PROFILE_TRANSACTIONS: '/trading/transactions/profile',
    STOCKS_SEARCH: '/trading/stocks/search',
    USERS_SEARCH: '/trading/users/search',
    FRIENDSHIPS: '/trading/friendships',
    FRIENDSHIP_REQUESTS: '/trading/friendships/requests',
    FRIENDSHIP_ACCEPT: (personId: number) => `/trading/friendships/${personId}/accept`,
    FRIENDSHIP_REJECT: (personId: number) => `/trading/friendships/${personId}/reject`,
    FRIENDSHIP_CANCEL_REQUEST: (personId: number) => `/trading/friendships/${personId}/request`,
    FRIENDSHIP_BLOCK: (personId: number) => `/trading/friendships/${personId}/block`,
    PORTFOLIO_HOLDINGS: (portfolioId: number) => `/trading/portfolio/${portfolioId}/holdings`,
    PORTFOLIO_BALANCE_HISTORY: (portfolioId: number) => `/trading/portfolio/${portfolioId}/balance-history`,
  },
  GROUPS: {
    CREATE: '/groups',
    SEARCH: '/groups/search',
    MINE: '/groups/mine',
    BY_ID: (groupId: number) => `/groups/${groupId}`,
    INVITE_TO_GROUP: (groupId: number) => `/groups/${groupId}/invites`,
    INVITES_PENDING: '/groups/invites/pending',
    INVITES_SENT: '/groups/invites/sent',
    INVITE_ACCEPT: (groupId: number) => `/groups/invites/${groupId}/accept`,
    INVITE_REJECT: (groupId: number) => `/groups/invites/${groupId}/reject`,
  },
};

export default ROUTES;
